disabled_rules:
- trailing_whitespace
- identifier_name
- type_name
excluded:
- Example
- Demo
- Carthage
- Pods
- .build
- LaymanTests/Core/CompilationBenchmarks
- LaymanTests/Operators/CompilationBenchmarks
line_length:
  warning: 180
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
cyclomatic_complexity:
    ignore_case_statements: true

